### PR TITLE
add eos tokens

### PR DESCRIPTION
**Pull request by eoskingdom**
add eos tokens

### CODE REVIEW

**Comment by gaijinjoe** [comment]
wrong format "<EKD>" to "EKD"

**Comment by eoskingdom** [comment]
correct wrong format

**Comment by eoskingdom** [comment]
格式已经纠正，麻烦通过下

**Comment by dfguo** [comment]
@eoskingdom there are some conflicts, please fix.

**Comment by eoskingdom** [comment]
已经修改

**Comment by eoskingdom** [comment]
@dfguo麻烦审核通过下

**Comment by eoskingdom** [comment]
Trouble review

**Pull request merged**
